version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=victor
      - POSTGRES_PASSWORD=password1234!
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=vm.navarro94@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password1234!
    ports:
      - 5050:80
